version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout

      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore

      # Build the project
      - run:
          name: Build
          command: dotnet build

      # Run tests
      - run:
          name: Run Tests
          command: dotnet test --logger:trx

workflows:
  version: 2
  build:
    jobs:
      - build
